### PR TITLE
Drag-and-drop Feature for Reordering Tasks

### LINKED ISSUE #11: Change the order of created tasks
Feature to use drag-and-drop to change the order of tasks in users' task lists.

### PR DESCRIPTION
**Pull request by justin569**
## Explanation for Implementation:
I used three events to handle the drag-and-drop: 
- _dragstart_ to indicate a task was now being dragged, and so I set a class to the task called `.dragging` to indicate that this task is the one currently being dragged. This is handled in the `Task` class with a simple listener.
- _dragover_ to notify the taskList to calculate the position to put the dragged task in when it is dropped. This is handled in 
- _dragend_ to indicate a drag is now finished, so we can update both the internal storage in taskList as well as localStorage.

### Notes:
- Everytime the task order is changed, or when the _dragend_ eventlistener executes, I change the ids of each task to match how they are presented visually. This means I also have to change the eventListeners for both the edit and delete functionalities, so, I unbind the old ones and bind new ones. I thought changing the ids was the better route instead of keeping them the same because we would probably complicate the localStorage and have to refactor a lot of the code, since we would also have to store the id for a given task.
- For the E2E testing, I used a plugin called [cypress-drag-drop](https://github.com/4teamwork/cypress-drag-drop) to help with testing, and I used it because one, it offers more flexibility for where you specify to drag/drop from. I also found a way to test it natively (it's commented out in the code), but I found that you can't specify an offset and are therefore limited in where you can drag/drop to.
- For the E2E testing, it will pass if you run it on your localhost url (since it has access to the new code for the new feature).
- Closes #11

### CODE REVIEW

**Comment by yitianwang18** [comment]
Hi Justin! I tested your code. It works on windows' chrome, edge, and firefox. It works on Linux Firefox. 
However it doesn't work on Linux Chrome, nor does it works with mobile touch events.

I will ask Rishmal about it. Meanwhile, could you try see if you can add mobile touch event supports for drag and drop?

**Comment by RishmalRohinkumar** [comment]
Matt messaged me about the mobile functionality and he was saying that it would be pretty complicated to add, so we agreed that he and Justin could push it to Sprint 3.

**Review by RishmalRohinkumar — APPROVED** [review]
All the code looks good. Great job on the comments, very detailed and it helped with understanding the code a lot. Thanks!

**Review by yitianwang18 — APPROVED** [review]
Looks good.

**Pull request merged**
